// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.5.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import "../frb_generated.dart";
import "package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart";

Future<void> setFolderPath(
        {required String cacheFolderPath,
        required String documentsFolderPath,
        required String downloadsFolderPath,
        required String supportFolderPath,
        required String temporaryFolderPath}) =>
    RustLib.instance.api.crateApiUtilsSetFolderPath(
        cacheFolderPath: cacheFolderPath,
        documentsFolderPath: documentsFolderPath,
        downloadsFolderPath: downloadsFolderPath,
        supportFolderPath: supportFolderPath,
        temporaryFolderPath: temporaryFolderPath);

Future<(int, int)> getImageSize({required String imagePath}) =>
    RustLib.instance.api.crateApiUtilsGetImageSize(imagePath: imagePath);

Future<String> getCurrentDevice() =>
    RustLib.instance.api.crateApiUtilsGetCurrentDevice();
